name: Cron Diagnostic

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes for testing
  workflow_dispatch:

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    steps:
      - name: Diagnostic Information
        run: |
          echo "🔍 CRON DIAGNOSTIC REPORT"
          echo "=========================="
          echo "Event type: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo ""
          echo "⏰ TIMING INFORMATION"
          echo "====================="
          echo "Current UTC time: $(date -u)"
          echo "Current local time: $(date)"
          echo "GitHub Actions timezone: UTC"
          echo ""
          echo "📅 SCHEDULE INFORMATION"
          echo "======================="
          echo "This workflow runs every 5 minutes"
          echo "Main cron job should run at: XX:00, XX:15, XX:30, XX:45"
          echo ""
          echo "🔧 REPOSITORY STATUS"
          echo "===================="
          echo "Repository visibility: ${{ github.repository_visibility }}"
          echo "Default branch: ${{ github.event.repository.default_branch }}"
          echo "Last commit: $(git log -1 --format='%H %s' --date=short)"
          echo ""
          echo "✅ DIAGNOSTIC COMPLETE"
          echo "====================="
          echo "If you see this message, cron jobs are working!"
          echo "Check the Actions tab for the main cron job runs."
          
      - name: Test HTTP Request
        run: |
          echo "🌐 Testing HTTP request capability..."
          
          # Test a simple HTTP request
          response=$(curl -s -w "\n%{http_code}" -X GET \
            https://httpbin.org/get \
            -H "User-Agent: GitHub-Actions-Cron-Test" 2>/dev/null || echo "Request failed")
          
          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | head -n -1)
          
          echo "HTTP Status: $http_code"
          echo "Response preview: ${response_body:0:100}..."
          
          if [ "$http_code" = "200" ]; then
            echo "✅ HTTP requests are working"
          else
            echo "❌ HTTP request failed"
          fi 