name: Fetch Dutchie Inventory Cron Job

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-inventory:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Supabase Edge Function
      run: |
        curl -X POST https://zpfrcsydbgxssojtsefg.supabase.co/functions/v1/fetch-dutchie-inventory \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
      
    - name: Log completion
      run: |
        echo "Dutchie inventory fetch completed at $(date)"
        echo "Check Supabase logs for detailed results" 