name: Cron Diagnostic

# This workflow helps diagnose GitHub Actions cron scheduling issues
on:
  schedule:
    # Test every 5 minutes for quick verification
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Repository Info
      run: |
        echo "🔍 CRON DIAGNOSTIC REPORT"
        echo "=========================="
        echo "Timestamp: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Visibility: ${{ github.repository_visibility }}"
        echo "Event: ${{ github.event_name }}"
        echo "Actor: ${{ github.actor }}"
        echo "Workflow: ${{ github.workflow }}"
        echo ""
        
        # Check if this is a scheduled run
        if [ "${{ github.event_name }}" = "schedule" ]; then
          echo "✅ This is a scheduled run (cron triggered)"
        else
          echo "⚠️  This is NOT a scheduled run (manual trigger)"
        fi
        
        echo ""
        echo "📋 CRON SCHEDULE INFO:"
        echo "Schedule: '*/5 * * * *' (every 5 minutes)"
        echo "Next expected runs:"
        echo "  - At minute 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55 of every hour"
        echo ""
        
        # Check GitHub Actions permissions
        echo "🔐 PERMISSIONS CHECK:"
        echo "Actions enabled: ${{ github.event.repository.allow_forking }}"
        echo "Default branch: ${{ github.event.repository.default_branch }}"
        echo ""
        
        # Test basic functionality
        echo "🧪 BASIC FUNCTIONALITY TEST:"
        echo "✅ GitHub Actions runner is working"
        echo "✅ Environment variables are accessible"
        echo "✅ Current time: $(date '+%Y-%m-%d %H:%M:%S %Z')"
        echo ""
        
        # Check if we can access secrets (without exposing them)
        if [ -n "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ]; then
          echo "✅ Secrets are accessible"
        else
          echo "⚠️  Secrets may not be accessible"
        fi
        
        echo ""
        echo "📝 TROUBLESHOOTING NOTES:"
        echo "1. Repository must be PUBLIC for free accounts"
        echo "2. Workflow must be on the DEFAULT BRANCH (main)"
        echo "3. At least one commit must be made after adding the schedule"
        echo "4. GitHub Actions must be enabled for the repository"
        echo "5. Cron syntax must be valid (UTC timezone)"
        echo ""
        echo "🎯 EXPECTED BEHAVIOR:"
        echo "- This workflow should run automatically every 5 minutes"
        echo "- Manual triggers should work immediately"
        echo "- Check Actions tab for run history"
        echo ""
        echo "🔗 USEFUL LINKS:"
        echo "- Actions tab: https://github.com/${{ github.repository }}/actions"
        echo "- Cron syntax: https://crontab.guru/"
        echo "- GitHub Actions docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule"
        
    - name: Test Edge Function
      run: |
        echo "🧪 TESTING EDGE FUNCTION:"
        echo "Making request to Supabase Edge Function..."
        
        # Test the edge function
        response=$(curl -s -w "\n%{http_code}" -X POST \
          https://zpfrcsydbgxssojtsefg.supabase.co/functions/v1/fetch-dutchie-inventory \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}' 2>/dev/null || echo "Request failed")
        
        http_code=$(echo "$response" | tail -n1)
        response_body=$(echo "$response" | head -n -1)
        
        echo "HTTP Status: $http_code"
        echo "Response: $response_body"
        
        if [ "$http_code" = "200" ]; then
          echo "✅ Edge function test successful"
        else
          echo "❌ Edge function test failed"
        fi
        
    - name: Final Status
      run: |
        echo ""
        echo "🏁 DIAGNOSTIC COMPLETE"
        echo "======================"
        echo "If you see this message, the workflow is running correctly."
        echo "Check the Actions tab for scheduled runs every 5 minutes."
        echo "Next scheduled run should be in ~5 minutes from now." 